name: Pre-commit

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - name: Install UV
      uses: astral-sh/setup-uv@v2
    - name: Install dependencies
      run: uv sync --dev
    - uses: pre-commit/action@v3.0.0 